# Generated by Django 5.2.1 on 2025-05-18 15:38

import django.core.validators
import django.db.models.deletion
import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('CARPET AND UPHOLSTERY', 'Carpet and Upholstery'), ('FLOOR CARE', 'Floor Care'), ('DISINFECTING', 'Disinfecting')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date', models.DateTimeField(validators=[my_app.models.validate_future_date])),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('discount_coupon', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'ordering': ['-date'],
            },
        ),
    ]
